--- 
- name: create /var/docker-compose/influxdb 
  file:
    path: "{{  item }}"
    state: directory
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:         
  - "/var/docker-compose/data/influxdb/data/lib/influxdb"

- name: Template influxdb files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: pi
    group: pi
  with_items:
  - { src: "env.influxdb.j2",           dest: "/var/docker-compose/data/influxdb/env.influxdb" }

- name: get_facts
  include_tasks: ../../../tasks/get_facts.yaml

- name: add to docker-compose
  include_tasks: docker-compose.yaml
