---
- name: create /var/docker-compose/home-assistance
  file:
    path: "{{  item }}"
    state: directory
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:
    - "/var/docker-compose/data/home-assistance/config"

- name: Create Docker files from template
  template:
    src: "configuration.yaml.j2"
    dest: "/var/docker-compose/data/home-assistance/config/configuration.yaml"
    mode: 0755
    owner: pi
    group: pi

- name: get_facts
  include_tasks: ../../../tasks/get_facts.yaml

- name: add to docker-compose
  include_tasks: docker-compose.yaml

- name: mount for backup
  include_tasks: backup